let Data = [
  {
    Name: "BBQ Chicken Flatbread",
    imgSrc: "images/BBQ Chicken.jpg",
    price: "10$",
    type: "Brakefast",
  },
  {
    Name: "Chicken Flatbread",
    imgSrc: "images/Chicken Flatbread.jpg",
    price: "42$",
    correctedTerm: "BBQ Chicken Flatbread",
    type: "Dinner",
  },
  {
    Name: "Tomato Mozzarella Flatbread",
    imgSrc: "images/Tomato Mozzarella Flatbread.jpg",
    price: "12$",
    type: "Brakefast",
  },
  {
    Name: "Roasted Turkey Cranberry Flatbread",
    imgSrc: "images/Roasted Turkey Cranberry Flatbread.jpg",
    price: "150$",
    type: "Brakefast",
  },
  {
    Name: "Turkey Cranberry Flatbread",
    imgSrc: "images/Roasted Turkey Cranberry Flatbread.jpg",
    price: "50$",
    type: "Evening",
  },
  {
    Name: "Half Size Italian on Hoagie Roll",
    imgSrc: "images/Half Size Italian on Hoagie Roll.jpg",
    price: "92$",
    type: "Lunch",
  },
  {
    Name: "Half Italian",
    imgSrc: "images/Half Italian.jpg",
    price: "27$",
    correctedTerm: "Half Size Italian on Hoagie Roll",
    type: "Lunch",
  },
  {
    Name: "Italian",
    imgSrc: "images/Italian.jpg",
    price: "5$",
    correctedTerm: "Italian on Hoagie Roll",
    type: "Dinner",
  },
  {
    Name: "Italian on Hoagie Roll",
    imgSrc: "images/Italian on Hoagie Roll.jpg",
    price: "34$",
    type: "Dinner",
  },
  {
    Name: "Steak and White Cheddar Panini",
    imgSrc: "images/Steak and White Cheddar Panini.jpg",
    price: "45$",
    type: "Evening",
  },
  {
    Name: "Steak and Cheddar Panini",
    imgSrc: "images/Steak and Cheddar Panini.jpg",
    price: "97$",
    type: "Brakefast",
  },
  {
    Name: "Steak Panini",
    imgSrc: "images/Steak Panini.jpg",
    price: "40$",
    correctedTerm: "Steak & White Cheddar Panini on Hoagie Roll",
    type: "Lunch",
  },
  {
    Name: "Steak & White Cheddar Panini on Hoagie Roll",
    imgSrc: "images/Steak & White Cheddar Panini on Hoagie Roll.jpg",
    price: "80$",
    type: "Brakefast",
  },
  {
    Name: "Half Steak Panini",
    imgSrc: "images/Half Steak Panini.jpg",
    price: "20$",
    correctedTerm: "Half Size Steak & White Cheddar Panini on Hoagie Roll",
    type: "Lunch",
  },
  {
    Name: "Half Size Steak & White Cheddar Panini on Hoagie Roll",
    imgSrc: "images/Half Size Steak & White Cheddar Panini on Hoagie Roll.jpg",
    price: "15$",
    type: "Evening",
  },
  {
    Name: "Chicken Panini",
    imgSrc: "images/Chicken Panini.jpg",
    price: "120$",
    correctedTerm: "Frontega Chicken Panini on Focaccia",
    type: "Brakefast",
  },
];
export default Data;
